;;; live.el --- dashboard-v3 P1 live check (batch) -*- lexical-binding: t; -*-
(require 'gascity)
(require 'cl-lib)
(defvar live-dir (getenv "GCE_DIR"))
(defvar live-phase "init")
(defvar live-max-gc 0)
(defvar live-gaps nil)
(defvar live-last (float-time))
(defvar live-msgs nil)
(advice-add 'message :before (lambda (fmt &rest args) (when (stringp fmt) (push (apply #'format-message fmt args) live-msgs))))
(defun live-count ()
  (cl-count-if (lambda (p) (and (process-live-p p)
                                (string-match-p "\\`gascity-gc\\(-action\\)?\\(<[0-9]+>\\)?\\'" (process-name p))))
               (process-list)))
(defun live-log (fmt &rest args)
  (princ (format "[%s %s] %s\n" (format-time-string "%T.%3N") live-phase (apply #'format fmt args))))
(run-with-timer 0.05 0.05
  (lambda ()
    (let* ((now (float-time)) (gap (- now live-last)))
      (when (> gap 0.25) (push (list live-phase gap) live-gaps))
      (setq live-last now
            live-max-gc (max live-max-gc (live-count))))))
(defun live-pump (secs pred)
  (let ((deadline (+ (float-time) secs)) (cap 100000))
    (while (and (> cap 0) (< (float-time) deadline) (not (funcall pred)))
      (setq cap (1- cap))
      (accept-process-output nil 0.05))))
(defun live-idle-p ()
  (let ((st (gascity-store-host-status live-dir)))
    (and (= 0 (plist-get st :reads)) (= 0 (plist-get st :actions))
         (= 0 (plist-get st :queued)))))
(defmacro live-timed (label &rest body)
  `(let ((t0 (float-time)))
     (prog1 (progn ,@body)
       (live-log "%s returned in %.3fs" ,label (- (float-time) t0)))))
(defun live-phase-summary ()
  (live-log "max concurrent gascity-gc processes: %d; stalls>250ms: %S"
            live-max-gc (reverse live-gaps))
  (setq live-max-gc 0 live-gaps nil))

(let ((default-directory live-dir))
  (setq live-phase "dashboard")
  (let ((buf (live-timed "gascity-dashboard" (save-window-excursion (gascity-dashboard) (current-buffer)))))
    (live-pump 3 (lambda () nil))
    (live-pump 60 #'live-idle-p)
    (live-log "idle; host status %S" (gascity-store-host-status live-dir))
    (with-current-buffer buf
      (write-region nil nil (concat temporary-file-directory "gascity-p1-dash-" (if (file-remote-p live-dir) "remote" "local") ".txt"))
      (live-log "dashboard buffer %s, %d lines; head:\n%s" (buffer-name buf)
                (count-lines (point-min) (point-max))
                (mapconcat #'identity (seq-take (split-string (buffer-string) "\n") 25) "\n"))))
  (live-phase-summary)
  ;; Contention: open more views of the same city at once.
  (setq live-phase "contention")
  (live-timed "status+sessions+rigs+mail"
    (save-window-excursion
      (ignore-errors (gascity-status))
      (gascity-session-list)
      (gascity-rig-list)
      (gascity-mail-inbox)))
  (live-pump 3 (lambda () nil))
  (live-pump 60 #'live-idle-p)
  (live-phase-summary)
  ;; Second open of the dashboard: served from the store.
  (setq live-phase "reopen")
  (let ((n0 (length (process-list))))
    (kill-buffer (get-buffer (gascity-remote-buffer-name "*gascity-dashboard*" nil (gascity-context-scope-key))))
    (live-timed "gascity-dashboard (warm, fresh mount)" (save-window-excursion (gascity-dashboard)))
    (live-log "processes started by warm reopen within TTL: %d" (- (length (process-list)) n0)))
  (live-pump 60 #'live-idle-p)
  (live-phase-summary)
  ;; Actions: mark a message read, then unread again (restores state).
  (setq live-phase "actions")
  (setq live-msgs nil)
  (live-timed "mark-read (async)"
    (gascity-command-act-async (gascity-command-mail-mark-read :id "bl-wisp-lu30rp")))
  (live-log "pending right after start: %S" (gascity-store-action-pending-p "bl-wisp-lu30rp"))
  (live-pump 30 (lambda () (not (gascity-store-action-pending-p "bl-wisp-lu30rp"))))
  (live-log "echo: %S" (car live-msgs))
  (live-timed "mark-unread (async)"
    (gascity-command-act-async (gascity-command-mail-mark-unread :id "bl-wisp-lu30rp")))
  (live-pump 30 (lambda () (not (gascity-store-action-pending-p "bl-wisp-lu30rp"))))
  (live-log "echo: %S" (car live-msgs))
  (live-timed "suspend nonexistent session (async)"
    (gascity-session-suspend "no-such-session-xyz"))
  (live-pump 30 (lambda () (not (gascity-store-action-pending-p "no-such-session-xyz"))))
  (live-log "echo: %S" (car live-msgs))
  (let ((log (get-buffer (gascity-store-log-buffer-name live-dir))))
    (live-log "log buffer %S:\n%s" (and log (buffer-name log))
              (and log (with-current-buffer log (buffer-string)))))
  (live-pump 60 #'live-idle-p)
  (live-phase-summary))
